# This is a basic workflow to help you get started with Actions

name: autodemo

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
           ref: 'dev'

    # Runs commands using the runners shell
    - name: Add line to file
      run: |
          echo 'demo' >> start.md
          
    - name: Commit files
      run: |
        git commit -m "Add changes" -a
        
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'dev'
        commit-message: 'demo'
        force-add: 'true'
        files: start.md




#    - name: Commit file
#      uses: swinton/commit@v2.x
#      env:
#        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        files: |
#          start.md
#        commit-message: demo
#        ref: refs/heads/dev
 

